Controllers/RingApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.SignalR;
using APIServerIot.models;
using APIServerIot.hubs;
namespace APIServerIot.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class RingApiController : ControllerBase
    {
      
        private readonly ILogger<RingApiController> _logger;
        private readonly IHubContext<RingHub> _hubContext;
        public RingApiController(ILogger<RingApiController> logger,IHubContext<RingHub> hub)
        {
            _logger = logger;
            _hubContext=hub;
         
        }

        [HttpPost]
            [Route("ringingStart")]
        public async Task ringingStart()
        {
            var model=new RingModel();
            model.Id=0;
            model.Ringing=true;
            model.StartAt=DateTime.Now;
            await _hubContext.Clients.All.SendAsync("ringMessage",model);           
        }

        [HttpPost]
        [Route("ringingEnd")]
        public async Task ringingEnd()
        {
            var model=new RingModel();
            model.Id=0;
            model.Ringing=false;
            model.EndAt=DateTime.Now;
            await _hubContext.Clients.All.SendAsync("ringMessage",model);           
        }
    }
}

Controllers/RingModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APIServerIot.models;

namespace APIServerIot.Controllers
{
    public class RingModelsController : Controller
    {

        // GET: RingModels
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

Views/RingModels/Index.cshtml
@{
    ViewData["Title"] = "Ring Bell";
}

<div class="bell-container">
<h1 id="bell-text">Attente de Sonnerie ....</h1>
<lottie-player id="bell" class="bell" background="transparent"  speed="1"  loop ></lottie-player>
</div>
<div class="audio-container">
<audio class="audio" preload="none">
    <source src="raw/zapsplat_household_doorbell_chime_classic_001_65580.mp3" type="audio/mpeg">
</audio>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sonnette App</title>
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bell.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="RingModels" asp-action="Index">Application de Sonnette</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RingModels" asp-action="Index">Sonnette</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RingModels" asp-action="Privacy">À propos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; ESAIP IoT Majeur - Sonnette Application - <a asp-area="" asp-controller="RingModels" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/soundmanager2/soundmanager2.js"></script>

    <script src="~/js/lottie/lottie-player.js"></script>
    <script src="~/js/bootstrap/bootstrap.bundle.min.js"></script>

    <script src="~/js/bell.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>